version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chatapp 

volumes:
  mongodbdata:
